CREATE DATABASE IF NOT EXISTS `BaguerdbExample`;
USE `BaguerdbExample`;

CREATE TABLE IF NOT EXISTS `User` (
    Id INT(11) NOT NULL AUTO_INCREMENT,
    Username VARCHAR(50) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    CONSTRAINT PkUser PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS `Empleado` (
    Id INT(11) NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(20) NOT NULL,
    Apellido VARCHAR(20) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    NombreImg VARCHAR(30) NOT NULL,
    TipoImg VARCHAR(30) NOT NULL,
    Img VARCHAR(255) NULL,
    Telefono INT(11) NULL,
    Direccion VARCHAR(100) NULL,
    Pais VARCHAR(30) NOT NULL,
    Ciudad VARCHAR(30) NULL,
    UserId INT(11) NOT NULL,
    CONSTRAINT PkEmpleado PRIMARY KEY (Id),
    CONSTRAINT FkUser FOREIGN KEY (UserId) REFERENCES User(Id),
);

CREATE TABLE IF NOT EXISTS `Imagen` (
    Id INT(11) NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(30) NOT NULL,
    Tipo VARCHAR(30) NOT NULL,
    Img VARCHAR(255) NULL,
    CONSTRAINT PkImg PRIMARY KEY (Id),
    EmpleadoId INT(11) NOT NULL,
    CONSTRAINT FkEmple FOREIGN KEY (EmpleadoId) REFERENCES User(Id),
);

