CREATE DATABASE IF NOT EXISTS `Baguerdb`;
USE `Baguerdb`;

CREATE TABLE IF NOT EXISTS `User` (
    Id INT(11) NOT NULL AUTO_INCREMENT,
    Username VARCHAR(50) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    CONSTRAINT PkUser PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS `Pais` (
    Id INT(11) NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(50) NOT NULL,
    CONSTRAINT PkPais PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS `Departamento` (
    Id INT(11) NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(50) NOT NULL,
    PaisId INT(11) NOT NULL,
    CONSTRAINT PkDepartamento PRIMARY KEY (Id),
    CONSTRAINT FkPaisDep FOREIGN KEY (PaisId) REFERENCES Pais(Id)

);

CREATE TABLE IF NOT EXISTS `Ciudad` (
    Id INT(11) NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(50) NOT NULL,
    DepartamentoId INT(11) NOT NULL,
    CONSTRAINT PkCiudad PRIMARY KEY (Id),
    CONSTRAINT FkDepartamentoCiu FOREIGN KEY (DepartamentoId) REFERENCES Departamento(Id)
);

CREATE TABLE IF NOT EXISTS `Empleado` (
    Id INT(11) NOT NULL AUTO_INCREMENT,
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Telefono INT(11) NULL,
    UserId INT(11) NOT NULL,
    CiudadId INT(11) NOT NULL,
    CONSTRAINT PkEmpleado PRIMARY KEY (Id),
    CONSTRAINT FkUser FOREIGN KEY (UserId) REFERENCES User(Id),
    CONSTRAINT FkCiudadEmp FOREIGN KEY (CiudadId) REFERENCES User(Id)
);

CREATE TABLE IF NOT EXISTS `Genero` (
    Id INT(11) NOT NULL AUTO_INCREMENT,
    Sexo CHAR(1) NOT NULL,
    EmpeladoId INT(11) NOT NULL,
    CONSTRAINT IdGenero PRIMARY KEY (Id),
    CONSTRAINT FkEmpeladoGen FOREIGN KEY (EmpeladoId) REFERENCES Empleado(Id)
);

CREATE TABLE IF NOT EXISTS `Imagen` (
    Id INT(11) NOT NULL AUTO_INCREMENT,
    Img BLOB NOT NULL,
    EmpeladoId INT(11) NOT NULL,
    CONSTRAINT IdImagen PRIMARY KEY (Id),
    CONSTRAINT FkEmpeladoImg FOREIGN KEY (EmpeladoId) REFERENCES Empleado(Id)
);


CREATE TABLE IF NOT EXISTS `Direccion` (
    Id INT(11) NOT NULL AUTO_INCREMENT,
    TipoVia VARCHAR(100) NOT NULL,
    Cardigan VARCHAR(100) NOT NULL,
    CodigoPostal INT(11) NOT NULL,
    EmpeladoId INT(11) NOT NULL,
    CONSTRAINT PkDireccion PRIMARY KEY (Id),
    CONSTRAINT FkEmpeladoDir FOREIGN KEY (EmpeladoId) REFERENCES Empleado(Id)
);



